source 'https://github.com/CocoaPods/Specs.git'

target 'InterfaceBuilderThemeFromCategories', :exclusive => true do
  pod "InterfaceBuilderThemeFromCategories", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "InterfaceBuilderThemeFromCategories", :path => "../"

  
end
